"! Has child class ZCL_XLOM_WORKSHEET.
CLASS zcl_xlom_sheet DEFINITION
  PUBLIC
  CREATE PRIVATE
  GLOBAL FRIENDS zcl_xlom_worksheet.

  PUBLIC SECTION.

  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.


CLASS zcl_xlom_sheet IMPLEMENTATION.
ENDCLASS.
